### ISSUE TITLE
Element <a class="_6hxp _6hxq" href="#">...</a> is not clickable at point (608, 527)

### ISSUE THREAD

**Issue by jcwelty** [justinlittman/fb-ad-archive-scraper#7]
I'm getting an error after about 70 posts, as part of process_ad_divs(). Seems like there's an issue with that element should be clicked? I'm not sure if there's a specific ad that's causing the problem, because for this search, it happens at a slightly different post count each time. any help would be greatly appreciated. Thanks!

Traceback (most recent call last):
  File "scraper_original.py", line 326, in <module>
    headless=not args.headed, wait=args.wait)
  File "scraper_original.py", line 197, in main
    process_ad_divs(new_ad_divs, len(processed_ad_divs), driver, dirname, ad_limit, wait=wait))
  File "scraper_original.py", line 76, in process_ad_divs
    ad_div.find_element_by_partial_link_text('See Ad Performance').click()
  File "C:\Users\jw\AppData\Local\conda\conda\envs\py36fbads\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\jw\AppData\Local\conda\conda\envs\py36fbads\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\jw\AppData\Local\conda\conda\envs\py36fbads\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "C:\Users\jw\AppData\Local\conda\conda\envs\py36fbads\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <a class="_6hxp _6hxq" href="#">...</a> is not clickable at point (608, 527). Other element would receive the click: <div class="_3ixn"></div>
  (Session info: headless chrome=69.0.3497.92)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.17134 x86_64)

**Comment by justinlittman** [comment]
Hmmm ... I've never run under Windows, so that may be part of the issue. What is the query that you're  using?

**Comment by jcwelty** [comment]
I'm actually getting a different error now, much earlier in the process:

Traceback (most recent call last):
  File "scraper.py", line 343, in <module>
    headless=not args.headed, wait=args.wait)
  File "scraper.py", line 199, in main
    assert ad_clazz
AssertionError

Getting this with lots of queries. Most recent was " trump --status active --country US"

**Comment by justinlittman** [comment]
If you run it with `-headed`, I suspect you'll find you're being blocked by Facebook (which is what is encountered while working on your ticket.)

**Comment by jcwelty** [comment]
Ah okay thanks. And that's just a rate limit thing? I've gotten it to work
since.
